import React from "react";
import Home from "../components/home/Home";

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};

const HomePage = () => {
  return (
    <div>
      <Home />
    </div>
  );
};

export default HomePage;
